apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproj-nio
  namespace: java-app
spec:
   replicas: 4
   selector:
    matchLabels:
      app: hello-world
   template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 184.73.211.202:8082/hello-world:195
        ports:
        - containerPort: 8080
