apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproj-nio
  namespace: java-app
spec:
   replicas: 4
   selector:
    matchLabels:
      app: hello-world
   template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world:195
        readinessProbe:
          httpGet:
            path: /
            port: 80
          successThreshold: 3
