apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: java-app
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30087
